### ISSUE TITLE
X509 JSON format: Output serial as string

### ISSUE THREAD

**Issue by andsens** [lukasz-lobocki/step-badger#28]
First of all thank you for making this open-source, and thank you for the effort! Works like a charm :heart: 

The `.Certificate.Serial` field is output as a float/number in JSON. Once you parse that with e.g. NodeJS and try to output it you get the scientific notation instead of the full base 10 string (e.g. `1.0834386045428302e+38` `108343860454283013782823752379123954236`). Now, it's pretty easy to just wrap that in a `BigInt`. But tbh, you're not really expected to do any math with those numbers (except maybe conversion to hex), they're identifiers.
  I suggest outputting the Base10 serial as a string.

EDIT: OK. Because of how floating points work it's actually even worse than that. The serial is plain wrong. I had to parse the raw cert and then use `BigInt('0x' + serial).toString()`. I suspect a lot of other languages that parse JSON ints as floating points will have the same issue.

**Comment by lukasz-lobocki** [comment]
Thank you @andsens, good catch. I will look into it in January, I have no access to my dev machine right now.

**Comment by lukasz-lobocki** [comment]
Hi @andsens, I looked into it. Unfortunately I am reluctant to change.

The output is produced by the standard `MarshalIndent` here:

https://github.com/lukasz-lobocki/step-badger/blob/51d7d3a7901391ead5f44cb934ef0066461badca/cmd/output_sshcerts.go#L87

It follows the standard type [Certificate struct](https://pkg.go.dev/golang.org/x/crypto/ssh#Certificate) that defines `Serial` as `uint64`. I do not want to introduce a custom behavior. I suggest, as you wrote, it should be wrapped in NodeJS `BigInt`.

Any input of yours is appreciated.

Happy New Year, Lukasz

**Comment by andsens** [comment]
Makes perfect sense. It's seldom good practice to put in workarounds for limitations on the consumer side.  
For anybody else stumbling across this: The proper workaround for JS would be to use a reviver function.
```
JSON.parse(
  '{"largeint":108343860454283013782823752379123954236}',
  (_, value) => isNaN(value) || Number.isSafeInteger(value) ? value : BigInt(value)
).largeint.toString();
# = '108343860454283018049479498025419145216' (instead of '1.0834386045428302e+38')
```

> Happy New Year

Likewise :-)

**Comment by lukasz-lobocki** [comment]
Hi, I did something else to workaround it.

There is the new node `StringSerials` added to json output. It contains string-formatted serials.

**Comment by andsens** [comment]
Oh, smart! Yeah, that makes sense. Good thinking, no breakage of the existing API 👍
